name: Build

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies && build
        run: |
          sudo apt update
          sudo apt install -y zip jq
          zip -r datapack.zip icon.png LICENSE pack.mcmeta README.md data version
          jq .mapcraft pack.mcmeta > release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
             datapack.zip
             release
